# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Java; end
module AboutDiceProject::DiceSet; end
module AboutJavaInterop::Java::JavaLang::Object; end
module AboutJavaInterop::Java::JavaUtil::HashMap; end
module AboutScope::Dog; end
module Neo::Sensei::JRUBY_VERSION; end
