name: dart_sample
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  characters: ^1.3.0
  path: ^1.8.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
