# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake', require: false
gem 'reek', require: false
gem 'rubocop', require: false
gem 'sorbet', group: :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, group: :development
